app:
  title: 'Christodoulou Law Ltd.'
  name: 'Christodoulou Law Ltd.'
  author: 'niden.net'
  description: 'Christodoulou Law Ltd. website'
  keywords: 'christodoulou, law, lawyers, construction'
  email: 'law@christodouloulaw.eu'

kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: true

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME



